<?php

use ArtPulse\Widgets\EventsWidget;
use ArtPulse\Widgets\OrgAnalyticsWidget;
use ArtPulse\Widgets\DonationsWidget;
use ArtPulse\Widgets\FavoritesOverviewWidget;
use ArtPulse\Widgets\MyUpcomingEventsWidget;
use ArtPulse\Widgets\ProfileOverviewWidget;
use ArtPulse\Widgets\WidgetEventsWidget;
use ArtPulse\Widgets\Member\ActivityFeedWidget;
use ArtPulse\Widgets\Member\WelcomeBoxWidget;
use ArtPulse\Core\DashboardWidgetRegistry;

return [
    'welcome_box' => [
        'class' => WelcomeBoxWidget::class,
        'label' => 'Welcome',
        'description' => 'Personal greeting for the signed-in user.',
        'roles' => ['member'],
        'category' => 'general',
        'icon' => 'smiley',
    ],
    'portfolio_preview' => [
        'callback' => [\ArtPulse\Widgets::class, 'render_portfolio_box'],
        'label' => 'Portfolio Overview',
        'description' => 'Summary of your published artworks.',
        'roles' => ['artist'],
        'category' => 'general',
        'icon' => 'portfolio',
    ],
    'org_insights' => [
        'callback' => [\ArtPulse\Widgets::class, 'render_org_insights_box'],
        'label' => 'Organization Insights',
        'description' => 'Key metrics for organization accounts.',
        'roles' => ['organization'],
        'category' => 'general',
        'icon' => 'chart-area',
    ],
    'activity_feed' => [
        'class' => ActivityFeedWidget::class,
        'label' => 'Activity Feed',
        'description' => 'Shows recent user and org activity',
        'roles' => ['member', 'artist', 'organization'],
        'category' => 'user',
        'icon' => 'activity',
        'cache' => true,
    ],
    'artist_inbox_preview' => [
        'callback' => 'ap_widget_artist_inbox_preview',
        'label' => 'Artist Inbox Preview',
        'description' => 'Recent unread messages from artists.',
        'roles' => ['member', 'artist'],
        'category' => 'engagement',
        'icon' => 'inbox',
        'capability' => 'can_receive_messages',
    ],
    'event_chat' => [
        'callback' => 'ap_widget_event_chat',
        'label' => 'Event Chat',
        'description' => 'Chat with other attendees.',
        'roles' => ['member'],
        'category' => 'events',
        'icon' => 'comments',
    ],
    'my_favorites' => [
        'callback' => [DashboardWidgetRegistry::class, 'render_widget_my_favorites'],
        'label' => 'My Favorite Events',
        'description' => 'Your saved events.',
        'roles' => ['member', 'artist'],
        'category' => 'general',
        'icon' => 'star',
    ],
    'nearby_events_map' => [
        'callback' => [DashboardWidgetRegistry::class, 'render_widget_nearby_events_map'],
        'label' => 'Nearby Events',
        'description' => 'Events around your location.',
        'roles' => ['member', 'artist'],
        'category' => 'general',
        'icon' => 'location',
    ],
    'news_feed' => [
        'class' => \ArtPulseNewsFeedWidget::class,
        'label' => 'ArtPulse News Feed',
        'description' => 'Latest posts from followed artists.',
        'roles' => ['member'],
        'category' => 'general',
        'icon' => 'rss',
    ],
    'qa_checklist' => [
        'class' => \QAChecklistWidget::class,
        'label' => 'QA Checklist',
        'description' => 'Steps to verify basic dashboard features.',
        'roles' => ['member'],
        'icon' => 'yes',
    ],
    'rsvp_button' => [
        'callback' => 'ap_widget_rsvp_button',
        'label' => 'RSVP Button',
        'description' => 'Toggle RSVP status for an event.',
        'roles' => ['member'],
        'category' => 'events',
        'icon' => 'calendar-check',
    ],
    'share_this_event' => [
        'callback' => 'ap_widget_share_this_event',
        'label' => 'Share This Event',
        'description' => 'Share this event with friends.',
        'roles' => ['member'],
        'category' => 'events',
        'icon' => 'share',
    ],
    'sample_events' => [
        'class' => EventsWidget::class,
        'label' => 'Events Widget',
        'description' => 'Sample upcoming events list.',
        'roles' => ['member', 'artist', 'organization'],
        'icon' => 'calendar',
        'category' => 'community',
        'cache' => true,
        'lazy' => true,
    ],
    'revenue_summary' => [
        'callback' => 'ap_widget_artist_revenue_summary',
        'label' => 'Revenue Summary',
        'description' => 'Revenue totals from tickets and donations.',
        'roles' => ['artist'],
        'category' => 'commerce',
        'icon' => 'chart-bar',
        'lazy' => true,
    ],
    'artist_spotlight' => [
        'callback' => 'ap_widget_artist_spotlight',
        'label' => 'Artist Spotlight',
        'description' => 'Recent mentions and highlights.',
        'roles' => ['artist'],
        'category' => 'community',
        'icon' => 'star-filled',
        'lazy' => true,
    ],
    'artist_artwork_manager' => [
        'callback' => 'ap_widget_artist_artwork_manager',
        'label' => 'Artwork Manager',
        'description' => 'Manage your artworks.',
        'roles' => ['artist'],
        'category' => 'general',
        'icon' => 'art',
        'lazy' => true,
    ],
    'artist_audience_insights' => [
        'callback' => 'ap_widget_artist_audience_insights',
        'label' => 'Audience Insights',
        'description' => 'View audience insights.',
        'roles' => ['artist'],
        'category' => 'analytics',
        'icon' => 'chart-pie',
        'lazy' => true,
    ],
    'artist_earnings_summary' => [
        'callback' => 'ap_widget_artist_earnings_summary',
        'label' => 'Earnings Summary',
        'description' => 'Overview of earnings from sales and tips.',
        'roles' => ['artist'],
        'category' => 'commerce',
        'icon' => 'money',
        'lazy' => true,
    ],
    'artist_feed_publisher' => [
        'callback' => 'ap_widget_artist_feed_publisher',
        'label' => 'Post & Engage',
        'description' => 'Publish updates to your feed.',
        'roles' => ['artist'],
        'category' => 'engagement',
        'icon' => 'megaphone',
        'lazy' => true,
    ],
    'collab_requests' => [
        'callback' => 'ap_widget_collab_requests',
        'label' => 'Collab Requests',
        'description' => 'Manage collaboration requests.',
        'roles' => ['artist'],
        'category' => 'community',
        'icon' => 'groups',
        'lazy' => true,
    ],
    'onboarding_tracker' => [
        'callback' => 'ap_widget_onboarding_tracker',
        'label' => 'Onboarding Checklist',
        'description' => 'Track setup tasks.',
        'roles' => ['artist'],
        'category' => 'general',
        'icon' => 'yes-alt',
        'lazy' => true,
    ],
    'audience_crm' => [
        'callback' => 'ap_widget_audience_crm',
        'label' => 'Audience CRM',
        'description' => 'Manage organization contacts.',
        'roles' => ['organization'],
        'icon' => 'groups',
        'lazy' => true,
    ],
    'sponsored_event_config' => [
        'callback' => 'ap_widget_sponsored_event_config',
        'label' => 'Sponsored Event Config',
        'description' => 'Configure sponsored event settings.',
        'roles' => ['organization'],
        'icon' => 'star',
        'lazy' => true,
    ],
    'embed_tool' => [
        'callback' => 'ap_widget_embed_tool',
        'label' => 'Embed Tool',
        'description' => 'Generate embeddable event widgets.',
        'roles' => ['organization'],
        'icon' => 'share',
        'lazy' => true,
    ],
    'org_event_overview' => [
        'callback' => 'ap_widget_org_event_overview',
        'label' => 'Event Overview',
        'description' => 'Overview of upcoming organization events.',
        'roles' => ['organization'],
        'icon' => 'calendar',
        'lazy' => true,
    ],
    'org_team_roster' => [
        'callback' => 'ap_widget_org_team_roster',
        'label' => 'Team Roster',
        'description' => 'List and manage team members.',
        'roles' => ['organization'],
        'icon' => 'admin-users',
        'lazy' => true,
    ],
    'branding_settings_panel' => [
        'callback' => 'ap_widget_branding_settings_panel',
        'label' => 'Branding Settings',
        'description' => 'Customize organization branding.',
        'roles' => ['organization'],
        'icon' => 'admin-customizer',
        'lazy' => true,
    ],
    'ap_donor_activity' => [
        'class' => \DonorActivityWidget::class,
        'label' => 'Donor Activity',
        'description' => 'Recent donations for your organization.',
        'roles' => ['organization'],
        'icon' => 'chart-line',
    ],
    'artpulse_analytics_widget' => [
        'class' => OrgAnalyticsWidget::class,
        'label' => 'Organization Analytics',
        'description' => 'Basic traffic and engagement metrics.',
        'roles' => ['organization'],
        'icon' => 'chart-bar',
    ],
    'org_widget_sharing' => [
        'callback' => 'ap_widget_org_widget_sharing',
        'label' => 'Widget Sharing',
        'description' => 'Share widgets with partners.',
        'roles' => ['organization'],
        'icon' => 'share',
        'lazy' => true,
    ],
    'webhooks' => [
        'callback' => 'ap_widget_webhooks',
        'label' => 'Webhooks',
        'description' => 'Manage outbound webhooks for automation.',
        'roles' => ['organization'],
        'icon' => 'admin-links',
    ],
    'sponsor_display' => [
        'callback' => 'ap_widget_sponsor_display',
        'label' => 'Sponsor Display',
        'description' => 'Showcase sponsors on events.',
        'roles' => ['organization'],
        'icon' => 'star-filled',
        'lazy' => true,
    ],
    'org_approval_center' => [
        'callback' => 'ap_widget_org_approval_center',
        'label' => 'Approval Center',
        'description' => 'Review pending items awaiting approval.',
        'roles' => ['organization'],
        'icon' => 'yes',
        'lazy' => true,
    ],
    'org_ticket_insights' => [
        'callback' => 'ap_widget_org_ticket_insights',
        'label' => 'Ticket Insights',
        'description' => 'Analyze ticket sales and attendance.',
        'roles' => ['organization'],
        'icon' => 'chart-line',
        'lazy' => true,
    ],
    'org_broadcast_box' => [
        'callback' => 'ap_widget_org_broadcast_box',
        'label' => 'Broadcast Box',
        'description' => 'Send messages to followers.',
        'roles' => ['organization'],
        'icon' => 'megaphone',
        'lazy' => true,
    ],
    'my_upcoming_events' => [
        'class' => MyUpcomingEventsWidget::class,
        'label' => 'My Upcoming Events',
        'description' => 'List of your upcoming events.',
        'roles' => ['member', 'artist'],
        'category' => 'events',
        'icon' => 'calendar',
    ],
    'profile_overview' => [
        'class' => ProfileOverviewWidget::class,
        'label' => 'Profile Overview',
        'description' => 'Quick stats about your profile.',
        'roles' => ['artist'],
        'category' => 'general',
        'icon' => 'user',
    ],
    'sample_donations' => [
        'class' => DonationsWidget::class,
        'label' => 'Donations Widget',
        'description' => 'Recent donations list.',
        'roles' => ['organization'],
        'category' => 'commerce',
        'icon' => 'money-alt',
    ],
    'widget_events' => [
        'class' => WidgetEventsWidget::class,
        'label' => 'Upcoming Events (Member)',
        'description' => 'Events happening soon.',
        'roles' => ['member', 'organization'],
        'category' => 'general',
        'icon' => 'calendar',
    ],
    'widget_favorites' => [
        'class' => FavoritesOverviewWidget::class,
        'label' => 'Favorites Overview',
        'description' => 'Your favorite artists and works.',
        'roles' => ['member'],
        'category' => 'general',
        'icon' => 'heart',
    ],
];
