<?php

use ArtPulse\Widgets\EventsWidget;
use ArtPulse\Widgets\OrgAnalyticsWidget;
use ArtPulse\Widgets\DonationsWidget;
use ArtPulse\Widgets\FavoritesOverviewWidget;
use ArtPulse\Widgets\NearbyEventsWidget;
use ArtPulse\Widgets\MyUpcomingEventsWidget;
use ArtPulse\Widgets\ProfileOverviewWidget;
use ArtPulse\Widgets\WidgetEventsWidget;
use ArtPulse\Widgets\Member\ActivityFeedWidget;
use ArtPulse\Widgets\Member\WelcomeBoxWidget;
use ArtPulse\Widgets\Member\EventChatWidget;
use ArtPulse\Widgets\Member\ArtistInboxPreviewWidget;
use ArtPulse\Widgets\Member\OrgTeamRosterWidget;
use ArtPulse\Core\DashboardWidgetRegistry;

return array_filter(
	array(
		'welcome_box'                      => array(
			'class'       => WelcomeBoxWidget::class,
			'label'       => 'Welcome',
			'description' => 'Personal greeting for the signed-in user.',
			'roles'       => array( 'member' ),
			'category'    => 'general',
			'icon'        => 'smiley',
		),
		'portfolio_preview'                => array(
			'callback'    => array( \ArtPulse\Widgets::class, 'render_portfolio_box' ),
			'label'       => 'Portfolio Overview',
			'description' => 'Summary of your published artworks.',
			'roles'       => array( 'artist' ),
			'category'    => 'general',
			'icon'        => 'portfolio',
		),
		'org_insights'                     => array(
			'callback'    => array( \ArtPulse\Widgets::class, 'render_org_insights_box' ),
			'label'       => 'Organization Insights',
			'description' => 'Key metrics for organization accounts.',
			'roles'       => array( 'organization' ),
			'category'    => 'general',
			'icon'        => 'chart-area',
		),
		'activity_feed'                    => ( defined( 'AP_DEV_MODE' ) && AP_DEV_MODE ) ? array(
			'class'       => ActivityFeedWidget::class,
			'label'       => 'Activity Feed',
			'description' => 'Shows recent user and org activity',
			'roles'       => array( 'member', 'artist', 'organization' ),
			'category'    => 'user',
			'icon'        => 'activity',
			'cache'       => true,
		) : null,
		'artist_inbox_preview'             => array(
			'class'       => ArtistInboxPreviewWidget::class,
			'label'       => 'Artist Inbox Preview',
			'description' => 'Recent unread messages from artists.',
			'roles'       => array( 'member', 'artist' ),
			'category'    => 'engagement',
			'icon'        => 'inbox',
			'capability'  => 'can_receive_messages',
		),
		'event_chat'                       => array(
			'class'       => EventChatWidget::class,
			'label'       => 'Event Chat',
			'description' => 'Chat with other attendees.',
			'roles'       => array( 'member' ),
			'category'    => 'events',
			'icon'        => 'comments',
		),
		'my_favorites'                     => array(
			'callback'    => array( DashboardWidgetRegistry::class, 'render_widget_my_favorites' ),
			'label'       => 'My Favorite Events',
			'description' => 'Your saved events.',
			'roles'       => array( 'member', 'artist' ),
			'category'    => 'general',
			'icon'        => 'star',
		),
		'nearby_events_map'                => array(
			'callback'    => array( DashboardWidgetRegistry::class, 'render_widget_nearby_events_map' ),
			'label'       => 'Nearby Events Map',
			'description' => 'Events around your location.',
			'roles'       => array( 'member', 'artist' ),
			'category'    => 'general',
			'icon'        => 'location',
		),
		'news_feed'                        => array(
			'class'       => \ArtPulseNewsFeedWidget::class,
			'label'       => 'ArtPulse News Feed',
			'description' => 'Latest posts from followed artists.',
			'roles'       => array( 'member' ),
			'category'    => 'general',
			'icon'        => 'rss',
		),
		'qa_checklist'                     => ( defined( 'AP_DEV_MODE' ) && AP_DEV_MODE ) ? array(
			'class'       => \QAChecklistWidget::class,
			'label'       => 'QA Checklist',
			'description' => 'Steps to verify basic dashboard features.',
			'roles'       => array( 'member' ),
			'icon'        => 'yes',
		) : null,
		'rsvp_button'                      => array(
			'callback'    => 'ap_widget_rsvp_button',
			'label'       => 'RSVP Button',
			'description' => 'Toggle RSVP status for an event.',
			'roles'       => array( 'member' ),
			'category'    => 'events',
			'icon'        => 'calendar-check',
		),
		'share_this_event'                 => array(
			'callback'    => 'ap_widget_share_this_event',
			'label'       => 'Share This Event',
			'description' => 'Share this event with friends.',
			'roles'       => array( 'member' ),
			'category'    => 'events',
			'icon'        => 'share',
		),
		'sample_events'                    => array(
			'class'       => EventsWidget::class,
			'label'       => 'Events Widget',
			'description' => 'Sample upcoming events list.',
			'roles'       => array( 'member', 'artist', 'organization' ),
			'icon'        => 'calendar',
			'category'    => 'community',
			'cache'       => true,
			'lazy'        => true,
		),
		'revenue_summary'                  => array(
			'callback'    => 'ap_widget_artist_revenue_summary',
			'label'       => 'Revenue Summary',
			'description' => 'Revenue totals from tickets and donations.',
			'roles'       => array( 'artist' ),
			'category'    => 'commerce',
			'icon'        => 'chart-bar',
			'lazy'        => true,
		),
		'artist_spotlight'                 => array(
			'callback'    => 'ap_widget_artist_spotlight',
			'label'       => 'Artist Spotlight',
			'description' => 'Recent mentions and highlights.',
			'roles'       => array( 'artist' ),
			'category'    => 'community',
			'icon'        => 'star-filled',
			'lazy'        => true,
		),
		'artist_artwork_manager'           => array(
			'callback'    => 'ap_widget_artist_artwork_manager',
			'label'       => 'Artwork Manager',
			'description' => 'Manage your artworks.',
			'roles'       => array( 'artist' ),
			'category'    => 'general',
			'icon'        => 'art',
			'lazy'        => true,
		),
		'artist_audience_insights'         => array(
			'callback'    => 'ap_widget_artist_audience_insights',
			'label'       => 'Audience Insights',
			'description' => 'View audience insights.',
			'roles'       => array( 'artist' ),
			'category'    => 'analytics',
			'icon'        => 'chart-pie',
			'lazy'        => true,
		),
		'artist_earnings_summary'          => array(
			'callback'    => 'ap_widget_artist_earnings_summary',
			'label'       => 'Earnings Summary',
			'description' => 'Overview of earnings from sales and tips.',
			'roles'       => array( 'artist' ),
			'category'    => 'commerce',
			'icon'        => 'money',
			'lazy'        => true,
		),
		'artist_feed_publisher'            => array(
			'callback'    => 'ap_widget_artist_feed_publisher',
			'label'       => 'Post & Engage',
			'description' => 'Publish updates to your feed.',
			'roles'       => array( 'artist' ),
			'category'    => 'engagement',
			'icon'        => 'megaphone',
			'lazy'        => true,
		),
		'collab_requests'                  => array(
			'callback'    => 'ap_widget_collab_requests',
			'label'       => 'Collab Requests',
			'description' => 'Manage collaboration requests.',
			'roles'       => array( 'artist' ),
			'category'    => 'community',
			'icon'        => 'groups',
			'lazy'        => true,
		),
		'onboarding_tracker'               => array(
			'callback'    => 'ap_widget_onboarding_tracker',
			'label'       => 'Onboarding Checklist',
			'description' => 'Track setup tasks.',
			'roles'       => array( 'artist' ),
			'category'    => 'general',
			'icon'        => 'yes-alt',
			'lazy'        => true,
		),
		'audience_crm'                     => array(
			'callback'    => 'ap_widget_audience_crm',
			'label'       => 'Audience CRM',
			'description' => 'Manage organization contacts.',
			'roles'       => array( 'organization' ),
			'icon'        => 'groups',
			'lazy'        => true,
		),
		'sponsored_event_config'           => array(
			'callback'    => 'ap_widget_sponsored_event_config',
			'label'       => 'Sponsored Event Config',
			'description' => 'Configure sponsored event settings.',
			'roles'       => array( 'organization' ),
			'icon'        => 'star',
			'lazy'        => true,
		),
		'embed_tool'                       => array(
			'callback'    => 'ap_widget_embed_tool',
			'label'       => 'Embed Tool',
			'description' => 'Generate embeddable event widgets.',
			'roles'       => array( 'organization' ),
			'icon'        => 'share',
			'lazy'        => true,
		),
		'widget_org_event_overview'        => array(
			'callback'    => 'ap_widget_org_event_overview',
			'label'       => 'Event Overview',
			'description' => 'Overview of upcoming organization events.',
			'roles'       => array( 'organization' ),
			'icon'        => 'calendar',
			'lazy'        => true,
		),
		'org_team_roster'                  => array(
			'class'       => OrgTeamRosterWidget::class,
			'label'       => 'Team Roster',
			'description' => 'List and manage team members.',
			'roles'       => array( 'organization' ),
			'icon'        => 'admin-users',
			'lazy'        => true,
		),
		'branding_settings_panel'          => array(
			'callback'    => 'ap_widget_branding_settings_panel',
			'label'       => 'Branding Settings',
			'description' => 'Customize organization branding.',
			'roles'       => array( 'organization' ),
			'icon'        => 'admin-customizer',
			'lazy'        => true,
		),
		'ap_donor_activity'                => array(
			'class'       => \DonorActivityWidget::class,
			'label'       => 'Donor Activity',
			'description' => 'Recent donations for your organization.',
			'roles'       => array( 'organization' ),
			'icon'        => 'chart-line',
		),
		'widget_artpulse_analytics_widget' => array(
			'class'       => OrgAnalyticsWidget::class,
			'label'       => 'Organization Analytics',
			'description' => 'Basic traffic and engagement metrics.',
			'roles'       => array( 'organization' ),
			'icon'        => 'chart-bar',
		),
		'org_widget_sharing'               => array(
			'callback'    => 'ap_widget_org_widget_sharing',
			'label'       => 'Widget Sharing',
			'description' => 'Share widgets with partners.',
			'roles'       => array( 'organization' ),
			'icon'        => 'share',
			'lazy'        => true,
		),
		'webhooks'                         => array(
			'callback'    => 'ap_widget_webhooks',
			'label'       => 'Webhooks',
			'description' => 'Manage outbound webhooks for automation.',
			'roles'       => array( 'organization' ),
			'icon'        => 'admin-links',
		),
		'sponsor_display'                  => array(
			'callback'    => 'ap_widget_sponsor_display',
			'label'       => 'Sponsor Display',
			'description' => 'Showcase sponsors on events.',
			'roles'       => array( 'organization' ),
			'icon'        => 'star-filled',
			'lazy'        => true,
		),
		'org_approval_center'              => array(
			'callback'    => 'ap_widget_org_approval_center',
			'label'       => 'Approval Center',
			'description' => 'Review pending items awaiting approval.',
			'roles'       => array( 'organization' ),
			'icon'        => 'yes',
			'lazy'        => true,
		),
		'org_ticket_insights'              => array(
			'callback'    => 'ap_widget_org_ticket_insights',
			'label'       => 'Ticket Insights',
			'description' => 'Analyze ticket sales and attendance.',
			'roles'       => array( 'organization' ),
			'icon'        => 'chart-line',
			'lazy'        => true,
		),
		'org_broadcast_box'                => array(
			'callback'    => 'ap_widget_org_broadcast_box',
			'label'       => 'Broadcast Box',
			'description' => 'Send messages to followers.',
			'roles'       => array( 'organization' ),
			'icon'        => 'megaphone',
			'lazy'        => true,
		),
		'my_upcoming_events'               => array(
			'class'       => MyUpcomingEventsWidget::class,
			'label'       => 'My Upcoming Events',
			'description' => 'List of your upcoming events.',
			'roles'       => array( 'member', 'artist' ),
			'category'    => 'events',
			'icon'        => 'calendar',
		),
		'profile_overview'                 => array(
			'class'       => ProfileOverviewWidget::class,
			'label'       => 'Profile Overview',
			'description' => 'Quick stats about your profile.',
			'roles'       => array( 'artist' ),
			'category'    => 'general',
			'icon'        => 'user',
		),
		'sample_donations'                 => array(
			'class'       => DonationsWidget::class,
			'label'       => 'Donations Widget',
			'description' => 'Recent donations list.',
			'roles'       => array( 'organization' ),
			'category'    => 'commerce',
			'icon'        => 'money-alt',
		),
		'widget_events'                    => array(
			'class'       => WidgetEventsWidget::class,
			'label'       => 'Upcoming Events (Member)',
			'description' => 'Events happening soon.',
			'roles'       => array( 'member', 'organization' ),
			'category'    => 'general',
			'icon'        => 'calendar',
		),
		'widget_near_me_events'            => array(
			'class'       => NearbyEventsWidget::class,
			'label'       => 'Nearby Events (Legacy)',
			'description' => 'Events near your location.',
			'roles'       => array( 'member' ),
			'category'    => 'general',
			'icon'        => 'location',
		),
		'widget_favorites'                 => array(
			'class'       => FavoritesOverviewWidget::class,
			'label'       => 'Favorites Overview',
			'description' => 'Your favorite artists and works.',
			'roles'       => array( 'member' ),
			'category'    => 'general',
			'icon'        => 'heart',
		),
	),
	function ( $item ) {
		return ! is_null( $item );
	}
);
