<?php

use ArtPulse\Widgets\EventsWidget;
use ArtPulse\Widgets\OrgAnalyticsWidget;

return [
    'activity_feed' => [
        'class' => \ActivityFeedWidget::class,
        'label' => 'Activity Feed',
        'description' => 'Shows recent user and org activity',
        'roles' => ['member', 'artist', 'organization'],
        'category' => 'user',
        'icon' => 'activity',
        'cache' => true,
    ],
    'artist_inbox_preview' => [
        'callback' => 'render_widget_artist_inbox_preview',
        'label' => 'Artist Inbox Preview',
        'description' => 'Recent unread messages from artists.',
        'roles' => ['member', 'artist'],
        'category' => 'engagement',
        'icon' => 'inbox',
        'capability' => 'can_receive_messages',
    ],
    'event_chat' => [
        'callback' => 'render_widget_event_chat',
        'label' => 'Event Chat',
        'description' => 'Chat with other attendees.',
        'roles' => ['member'],
        'category' => 'events',
        'icon' => 'comments',
    ],
    'my_favorites' => [
        'callback' => 'render_widget_my_favorites',
        'label' => 'My Favorite Events',
        'description' => 'Your saved events.',
        'roles' => ['member', 'artist'],
        'category' => 'general',
        'icon' => 'star',
    ],
    'nearby_events_map' => [
        'callback' => 'render_widget_nearby_events_map',
        'label' => 'Nearby Events',
        'description' => 'Events around your location.',
        'roles' => ['member', 'artist'],
        'category' => 'general',
        'icon' => 'location',
    ],
    'news_feed' => [
        'class' => \ArtPulseNewsFeedWidget::class,
        'label' => 'ArtPulse News Feed',
        'description' => 'Latest posts from followed artists.',
        'roles' => ['member'],
        'category' => 'general',
        'icon' => 'rss',
    ],
    'qa_checklist' => [
        'class' => \QAChecklistWidget::class,
        'label' => 'QA Checklist',
        'description' => 'Steps to verify basic dashboard features.',
        'roles' => ['member'],
        'icon' => 'yes',
    ],
    'rsvp_button' => [
        'callback' => 'render_widget_rsvp_button',
        'label' => 'RSVP Button',
        'description' => 'Toggle RSVP status for an event.',
        'roles' => ['member'],
        'category' => 'events',
        'icon' => 'calendar-check',
    ],
    'share_this_event' => [
        'callback' => 'render_widget_share_this_event',
        'label' => 'Share This Event',
        'description' => 'Share this event with friends.',
        'roles' => ['member'],
        'category' => 'events',
        'icon' => 'share',
    ],
    'sample_events' => [
        'class' => EventsWidget::class,
        'label' => 'Events Widget',
        'description' => 'Sample upcoming events list.',
        'roles' => ['member', 'artist', 'organization'],
        'icon' => 'calendar',
        'category' => 'community',
        'cache' => true,
        'lazy' => true,
    ],
    'audience_crm' => [
        'callback' => 'render_widget_audience_crm',
        'label' => 'Audience CRM',
        'description' => 'Manage organization contacts.',
        'roles' => ['organization'],
        'icon' => 'groups',
        'lazy' => true,
    ],
    'sponsored_event_config' => [
        'callback' => 'render_widget_sponsored_event_config',
        'label' => 'Sponsored Event Config',
        'description' => 'Configure sponsored event settings.',
        'roles' => ['organization'],
        'icon' => 'star',
        'lazy' => true,
    ],
    'embed_tool' => [
        'callback' => 'render_widget_embed_tool',
        'label' => 'Embed Tool',
        'description' => 'Generate embeddable event widgets.',
        'roles' => ['organization'],
        'icon' => 'share',
        'lazy' => true,
    ],
    'org_event_overview' => [
        'callback' => 'render_widget_org_event_overview',
        'label' => 'Event Overview',
        'description' => 'Overview of upcoming organization events.',
        'roles' => ['organization'],
        'icon' => 'calendar',
        'lazy' => true,
    ],
    'org_team_roster' => [
        'callback' => 'render_widget_org_team_roster',
        'label' => 'Team Roster',
        'description' => 'List and manage team members.',
        'roles' => ['organization'],
        'icon' => 'admin-users',
        'lazy' => true,
    ],
    'branding_settings_panel' => [
        'callback' => 'render_widget_branding_settings_panel',
        'label' => 'Branding Settings',
        'description' => 'Customize organization branding.',
        'roles' => ['organization'],
        'icon' => 'admin-customizer',
        'lazy' => true,
    ],
    'ap_donor_activity' => [
        'class' => \DonorActivityWidget::class,
        'label' => 'Donor Activity',
        'description' => 'Recent donations for your organization.',
        'roles' => ['organization'],
        'icon' => 'chart-line',
    ],
    'artpulse_analytics_widget' => [
        'class' => OrgAnalyticsWidget::class,
        'label' => 'Organization Analytics',
        'description' => 'Basic traffic and engagement metrics.',
        'roles' => ['organization'],
        'icon' => 'chart-bar',
    ],
    'org_widget_sharing' => [
        'callback' => 'render_widget_org_widget_sharing',
        'label' => 'Widget Sharing',
        'description' => 'Share widgets with partners.',
        'roles' => ['organization'],
        'icon' => 'share',
        'lazy' => true,
    ],
    'webhooks' => [
        'callback' => 'render_widget_webhooks',
        'label' => 'Webhooks',
        'description' => 'Manage outbound webhooks for automation.',
        'roles' => ['organization'],
        'icon' => 'admin-links',
    ],
    'sponsor_display' => [
        'callback' => 'render_widget_sponsor_display',
        'label' => 'Sponsor Display',
        'description' => 'Showcase sponsors on events.',
        'roles' => ['organization'],
        'icon' => 'star-filled',
        'lazy' => true,
    ],
    'org_approval_center' => [
        'callback' => 'render_widget_org_approval_center',
        'label' => 'Approval Center',
        'description' => 'Review pending items awaiting approval.',
        'roles' => ['organization'],
        'icon' => 'yes',
        'lazy' => true,
    ],
    'org_ticket_insights' => [
        'callback' => 'render_widget_org_ticket_insights',
        'label' => 'Ticket Insights',
        'description' => 'Analyze ticket sales and attendance.',
        'roles' => ['organization'],
        'icon' => 'chart-line',
        'lazy' => true,
    ],
    'org_broadcast_box' => [
        'callback' => 'render_widget_org_broadcast_box',
        'label' => 'Broadcast Box',
        'description' => 'Send messages to followers.',
        'roles' => ['organization'],
        'icon' => 'megaphone',
        'lazy' => true,
    ],
];
