<?php
return array(
	'ap_donor_activity'         => 'widget_ap_donor_activity',
	'artist_inbox_preview'      => 'widget_artist_inbox_preview',
	'artist_spotlight'          => 'widget_artist_spotlight',
	'artpulse_analytics_widget' => 'widget_artpulse_analytics_widget',
	'audience_crm'              => 'widget_audience_crm',
	'branding_settings_panel'   => 'widget_branding_settings_panel',
	'embed_tool'                => 'widget_embed_tool',
	'event_chat'                => 'widget_event_chat',
	'my_favorites'              => 'widget_my_favorites',
	'nearby_events_map'         => 'widget_nearby_events_map',
        'news_feed'                 => 'widget_news',
	'org_widget_sharing'        => 'widget_org_widget_sharing',
	'revenue_summary'           => 'widget_revenue_summary',
	'artist_artwork_manager'    => 'widget_artist_artwork_manager',
	'artist_audience_insights'  => 'widget_artist_audience_insights',
	'artist_earnings_summary'   => 'widget_artist_earnings_summary',
	'artist_feed_publisher'     => 'widget_artist_feed_publisher',
	'collab_requests'           => 'widget_collab_requests',
	'onboarding_tracker'        => 'widget_onboarding_tracker',
	'rsvp_button'               => 'widget_rsvp_button',
	'share_this_event'          => 'widget_share_this_event',
	'sponsor_display'           => 'widget_sponsor_display',
	'sponsored_event_config'    => 'widget_sponsored_event_config',
	'webhooks'                  => 'widget_webhooks',
	'widget_events'             => 'widget_events',
	'widget_favorites'          => 'widget_favorites',
	'org_event_overview'        => 'widget_org_event_overview',
	'org_team_roster'           => 'widget_org_team_roster',
	'org_approval_center'       => 'widget_org_approval_center',
	'org_ticket_insights'       => 'widget_org_ticket_insights',
	'org_broadcast_box'         => 'widget_org_broadcast_box',
);
