<?php
return array (
  'ap_donor_activity' => 'widget_ap_donor_activity',
  'artist_inbox_preview' => 'widget_artist_inbox_preview',
  'artist_spotlight' => 'widget_artist_spotlight',
  'artpulse_analytics_widget' => 'widget_artpulse_analytics_widget',
  'audience_crm' => 'widget_audience_crm',
  'branding_settings_panel' => 'widget_branding_settings_panel',
  'embed_tool' => 'widget_embed_tool',
  'event_chat' => 'widget_event_chat',
  'my_favorites' => 'widget_my_favorites',
  'nearby_events_map' => 'widget_nearby_events_map',
  'news_feed' => 'widget_news_feed',
  'org_widget_sharing' => 'widget_org_widget_sharing',
  'qa_checklist' => 'widget_qa_checklist',
  'revenue_summary' => 'widget_revenue_summary',
  'rsvp_button' => 'widget_rsvp_button',
  'share_this_event' => 'widget_share_this_event',
  'sponsor_display' => 'widget_sponsor_display',
  'sponsored_event_config' => 'widget_sponsored_event_config',
  'webhooks' => 'widget_webhooks',
  'widget_events' => 'widget_events',
  'widget_favorites' => 'widget_favorites',
);
