# Bundle size checks with size-limit
name: bundlesize

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bundlesize:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        node: [20.x] # Use latest LTS for build tooling
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check size
        id: size
        run: |
          mkdir -p artifacts/bundlesize
          npx size-limit --json > artifacts/bundlesize/report.json
          node <<'NODE' > artifacts/bundlesize/table.md
          const fs=require('fs');
          const data=JSON.parse(fs.readFileSync('artifacts/bundlesize/report.json','utf8'));
          console.log('| Bundle | Size (KB) | Limit (KB) |\n| --- | --- | --- |');
          data.forEach(r=>console.log(`| ${r.name} | ${(r.size/1024).toFixed(2)} | ${(r.limit/1024).toFixed(2)} |`));
NODE

      - name: Upload artifacts
        if: always()
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: bundlesize-${{ matrix.node }}
          path: artifacts/bundlesize/

      - name: Job summary
        if: always()
        run: |
          icon="❌"; [ "${{ job.status }}" = "success" ] && icon="✅"
          echo '| Result | Artifact |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo "| $icon | [report](${{ steps.upload.outputs.artifact-url }}) |" >> $GITHUB_STEP_SUMMARY
          cat artifacts/bundlesize/table.md >> $GITHUB_STEP_SUMMARY
