name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php:
    name: PHP (PHPUnit)
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer:v2

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP deps
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Setup WordPress tests
        run: bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest

      - name: Run PHPUnit
        run: |
          vendor/bin/phpunit -c phpunit.unit.xml.dist
          WP_PHPUNIT__DIR=vendor/wp-phpunit/wp-phpunit \
          WP_TESTS_CONFIG_FILE_PATH=wp-tests-config.php \
          DB_NAME=wordpress_test \
          DB_USER=root \
          DB_PASSWORD=root \
          DB_HOST=127.0.0.1 \
          WP_CORE_DIR=/tmp/wordpress \
          AP_TEST_MODE=1 \
          vendor/bin/phpunit -c phpunit.wp.xml.dist

  js:
    name: JS (Jest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install JS deps
        run: npm ci

      - name: Run Jest
        env:
          CI: 'true'
        run: npm test -- --runInBand
