name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-php@v3
        with:
          php-version: '8.3'
      - run: composer install --prefer-dist --no-progress
      - run: npm install
      - run: composer test
      - run: composer sniff
