name: dependency-audit

on:
  pull_request:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - name: NPM audit
        run: npm audit --omit=dev || true
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          coverage: none
      - name: Composer install
        run: composer install --no-progress --no-interaction
      - name: Composer audit
        run: composer audit || true
      - name: Summary
        run: |
          echo "### Dependency audit" >> $GITHUB_STEP_SUMMARY
          echo "- npm and composer audits executed" >> $GITHUB_STEP_SUMMARY
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }}-${{ github.job }}-logs
          path: |
            **/test-results/**/*.xml
            **/logs/**
          if-no-files-found: ignore
      - name: Job summary
        if: always()
        run: |
          echo "### ${{ github.workflow }} / ${{ github.job }}" >> $GITHUB_STEP_SUMMARY
          echo "- status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
