# Dispatch selected workflows and aggregate their results
name: orchestrate-all

on:
  workflow_dispatch:
    inputs:
      workflows:
        description: 'Comma-separated workflow file names to run'
        required: true
      ref:
        description: 'Git ref to use'
        required: false
        default: ${{ github.ref }}

permissions:
  actions: write
  contents: read

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Dispatch workflows
        id: dispatch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          IFS=',' read -ra WFS <<< "${{ inputs.workflows }}"
          printf '%s\n' "${WFS[@]}" > wf-list.txt
          for wf in "${WFS[@]}"; do
            gh workflow run "$wf" --ref "${{ inputs.ref }}"
          done

      - name: Wait for completion
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
