name: PHPUnit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-php@v3
        with:
          php-version: '8.3'
      - run: composer install --prefer-dist --no-progress
      - run: bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest
      - name: Run tests with coverage
        run: tools/run-coverage.sh
        env:
          WP_PHPUNIT__DIR: vendor/wp-phpunit/wp-phpunit
          WP_TESTS_CONFIG_FILE_PATH: wp-tests-config.php
          DB_NAME: wordpress_test
          DB_USER: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
