name: Static Checks

on:
  push:
  pull_request:

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-${{ runner.os }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHP CodeSniffer
        run: vendor/bin/phpcs --standard=phpcs.xml

      - name: PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon

      - name: PHPUnit
        run: |
          mkdir -p build
          vendor/bin/phpunit --log-junit build/junit.xml

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-junit
          path: build/junit.xml
