name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - run: composer install --no-interaction --no-progress

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci || npm install

      - name: WordPress tests
        run: composer run test:php:wp || true
        env:
          WP_PHPUNIT__DIR: vendor/wp-phpunit/wp-phpunit

      - name: PHP unit tests
        run: composer run test:php:unit || true

      - name: Jest tests
        run: npm run test:js || true

      - name: Start application
        run: |
          npm start &
          echo $! > server.pid
          npx wait-on http://localhost:3000 --timeout 60000

      - name: Playwright tests
        run: npm run test:e2e || true

      - name: Stop application
        run: kill $(cat server.pid) || true

      - name: Aggregate results
        run: npm run test:summary

      - uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            build/
            coverage/

