name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - run: composer install --no-interaction --no-progress

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci || npm install

      - name: WordPress tests
        id: wp_tests
        continue-on-error: true
        run: composer run test:php:wp
        env:
          WP_PHPUNIT__DIR: vendor/wp-phpunit/wp-phpunit

      - name: PHP unit tests
        id: php_unit_tests
        continue-on-error: true
        run: composer run test:php:unit

      - name: Jest tests
        id: jest_tests
        continue-on-error: true
        run: npm run test:js

      - name: Playwright tests
        id: playwright_tests
        continue-on-error: true
        run: npm run test:e2e

      - name: Aggregate results
        run: npm run test:summary

      - uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            build/
            coverage/

      - name: Fail if tests failed
        if: steps.wp_tests.outcome == 'failure' || steps.php_unit_tests.outcome == 'failure' || steps.jest_tests.outcome == 'failure' || steps.playwright_tests.outcome == 'failure'
        run: exit 1

