# WordPress Coding Standards via PHPCS
name: wp-coding-standards

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  phpcs:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3'] # Ensure compatibility with supported PHP versions
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Run PHPCS
        id: phpcs
        run: |
          mkdir -p artifacts/phpcs
          SECONDS=0
          composer exec -- phpcs --standard=phpcs.xml.dist --report-full > artifacts/phpcs/report.txt || exit_code=$?
          echo "duration=$SECONDS" >> $GITHUB_OUTPUT
          echo "exit=${exit_code:-0}" >> $GITHUB_OUTPUT
          errs=$(tail -n1 artifacts/phpcs/report.txt | grep -oP '(\d+) errors' | awk '{print $1}')
          warns=$(tail -n1 artifacts/phpcs/report.txt | grep -oP '(\d+) warnings' | awk '{print $1}')
          echo "errors=${errs:-0}" >> $GITHUB_OUTPUT
          echo "warnings=${warns:-0}" >> $GITHUB_OUTPUT
          if [ "${exit_code:-0}" -ne 0 ]; then exit ${exit_code:-0}; fi

      - name: Upload artifacts
        if: always()
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: phpcs-${{ matrix.php }}
          path: artifacts/phpcs/

      - name: Job summary
        if: always()
        run: |
          icon="❌"; [ "${{ steps.phpcs.outputs.exit }}" = "0" ] && icon="✅"
          echo '| PHP | Result | Duration (s) | Errors | Warnings | Artifacts |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- | --- | --- | --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo "| ${{ matrix.php }} | $icon | ${{ steps.phpcs.outputs.duration }} | ${{ steps.phpcs.outputs.errors }} | ${{ steps.phpcs.outputs.warnings }} | [report](${{ steps.upload.outputs.artifact-url }}) |" >> $GITHUB_STEP_SUMMARY
