# Lightweight WordPress integration smoke tests
name: wp-integration-tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  wp:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2'] # Supported PHP versions
        wordpress: ['6.5', '6.6'] # Recent WP releases
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Start environment and smoke test
        id: test
        run: |
          mkdir -p artifacts/wp
          SECONDS=0
          npx wp-env start --wordpress-version=${{ matrix.wordpress }} --php-version=${{ matrix.php }} > artifacts/wp/start.log 2>&1
          npx wp-env run cli "wp plugin activate artpulse" >> artifacts/wp/start.log 2>&1 || true
          curl -fsS http://localhost:8888/wp-json/artpulse/v1/dashboard-config -o artifacts/wp/response.json
          echo "duration=$SECONDS" >> $GITHUB_OUTPUT
        shell: bash

      - name: Stop environment
        if: always()
        run: npx wp-env stop

      - name: Upload artifacts
        if: always()
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: wp-integration-${{ matrix.php }}-wp${{ matrix.wordpress }}
          path: artifacts/wp/

      - name: Job summary
        if: always()
        run: |
          icon="❌"; [ "${{ job.status }}" = "success" ] && icon="✅"
          echo '| PHP | WP | Result | Duration (s) | Artifacts |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- | --- | --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo "| ${{ matrix.php }} | ${{ matrix.wordpress }} | $icon | ${{ steps.test.outputs.duration }} | [logs](${{ steps.upload.outputs.artifact-url }}) |" >> $GITHUB_STEP_SUMMARY
